### ISSUE TITLE
IPWhois("reserved_ip") return traceback

### ISSUE THREAD

**Issue by cgi1** [secynic/ipwhois#208]
`ipwhois_obj = IPWhois('249.176.139.93')`

leads to

```
Traceback (most recent call last):
  File "/home/administrator/g2/g2/g2/modules/data_sources/whois.py", line 101, in gather_data
    ipwhois_obj = IPWhois(self.model.value)
  File "/usr/local/lib/python3.5/dist-packages/ipwhois/ipwhois.py", line 55, in __init__
    allow_permutations=allow_permutations
  File "/usr/local/lib/python3.5/dist-packages/ipwhois/net.py", line 172, in __init__
    self.address_str, is_defined[1], is_defined[2]
ipwhois.exceptions.IPDefinedError: IPv4 address 249.176.139.93 is already defined as Private-Use Networks via RFC 1918.
```

**Comment by secynic** [comment]
This is the correct outcome. This address space is "Reserved for future use":
https://tools.ietf.org/html/rfc6890#section-2.2.2

This check is done via a call to the built-in ipaddress library's is_private function:
https://github.com/secynic/ipwhois/blob/master/ipwhois/utils.py#L348

I would wrap all of your IPWhois calls with exception handling. In this case, look for ipwhois.exceptions.IPDefinedError.
