### ISSUE TITLE
Unable to get ipwhois result

### ISSUE THREAD

**Issue by selvam33** [secynic/ipwhois#211]
I am trying to get the basic result of an IP using ipwhois on python 2.7, got below error. Please advise !!!

>>> obj = IPWhois('12.0.68.200')
/usr/lib/python2.7/site-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
>>> obj = IPWhois('12.0.68.200')
>>> res = obj.lookup_whois()
/usr/lib/python2.7/site-packages/ipwhois/asn.py:178: UserWarning: IPASN._parse_fields_dns() has been deprecated and will be removed. You should now use IPASN.parse_fields_dns().
  warn('IPASN._parse_fields_dns() has been deprecated and will be '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ipwhois/ipwhois.py", line 179, in lookup_whois
    field_list=field_list
  File "/usr/lib/python2.7/site-packages/ipwhois/whois.py", line 678, in lookup
    extra_blacklist=extra_blacklist
  File "/usr/lib/python2.7/site-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/lib/python2.7/site-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/lib/python2.7/site-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/lib/python2.7/site-packages/ipwhois/net.py", line 655, in get_whois
    'WHOIS lookup failed for {0}.'.format(self.address_str)
ipwhois.exceptions.WhoisLookupError: WHOIS lookup failed for 12.0.68.200.

**Comment by selvam33** [comment]
my issue resolved after opening the port 43. Thanks !!!
