### ISSUE TITLE
Spanish whois: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 50: ordinal not in range(128)

### ISSUE THREAD

**Issue by shakaran** [secynic/ipwhois#256]
I get the following error searching via whois ARP 46.25.1.44:

```
Traceback (most recent call last):
  File "/usr/local/bin/ipwhois_cli.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/root/src/ipwhois/ipwhois/scripts/ipwhois_cli.py", line 1481, in <module>
    get_asn_description=(not script_args.skip_asn_description)
  File "/root/src/ipwhois/ipwhois/scripts/ipwhois_cli.py", line 1059, in lookup_rdap
    json_data=ret, hr=hr, show_name=show_name, colorize=colorize
  File "/root/src/ipwhois/ipwhois/scripts/ipwhois_cli.py", line 974, in generate_output_objects
    i_value
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 50: ordinal not in range(128)
```

The normal output via the whois command is throwing this data:

```
$ whois 46.25.1.44
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '46.25.0.0 - 46.25.24.255'

% Abuse contact for '46.25.0.0 - 46.25.24.255' is 'abuse@corp.vodafone.es'

inetnum:        46.25.0.0 - 46.25.24.255
netname:        IPCOM-NET
descr:          VODAFONE ESPANA, S.A.U.
descr:          VODAFONE-Broadband
descr:          Infraestructura Red y Servicios IP
country:        ES
admin-c:        PRC8-RIPE
tech-c:         PRC8-RIPE
status:         ASSIGNED PA
mnt-by:         COMUNITEL-MNT
created:        2019-04-25T15:59:35Z
last-modified:  2019-04-25T15:59:35Z
source:         RIPE

role:           Planificacion RMS Comunitel
address:        Oficina Vodafone Bouzas I (oficina Comercial Vigo)
address:        Consorcio. Zona Franca Bouzas.
address:        36208 Vigo Espanha
remarks:        Grupo de Planificacion Broadband
abuse-mailbox:  abuse@corp.vodafone.es
admin-c:        ACG18-RIPE
tech-c:         SRO19-RIPE
tech-c:         RMD13-RIPE
tech-c:         ACG18-RIPE
tech-c:         ERP9-RIPE
tech-c:         ISC17-RIPE
tech-c:         RLC13-RIPE
tech-c:         MTP58-RIPE
nic-hdl:        PRC8-RIPE
mnt-by:         COMUNITEL-MNT
created:        2008-11-06T12:08:42Z
last-modified:  2011-12-22T12:18:12Z
source:         RIPE # Filtered

% Information related to '46.25.0.0/21AS12357'

route:          46.25.0.0/21
descr:          Vodafone-BB Global PA Block
origin:         AS12357
mnt-by:         COMUNITEL-MNT
created:        2016-07-12T07:02:21Z
last-modified:  2016-07-12T07:02:21Z
source:         RIPE

% This query was served by the RIPE Database Query Service version 1.97 (HEREFORD)

```

I get this same error for other ips like 95.61.100.240, 5.225.8.38

**Comment by secynic** [comment]
Are you still having this issue? I was not able to reproduce using the IPs provided.
