### ISSUE TITLE
118.27.81.0/24 crash

### ISSUE THREAD

**Issue by automatize-it** [secynic/ipwhois#266]
```
ipwhois_cli.py --addr 118.27.81.1

ipwhois\net.py:138: UserWarning: a llow_permutations has been deprecated and will be removed. It is no longer neede
d, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
Traceback (most recent call last):
  File "C:\Program Files\Python_2.7\Scripts\ipwhois_cli.py", line 1514, in <module> 
get_asn_description=(not script_args.skip_asn_description)
  File "C:\Program Files\Python_2.7\Scripts\ipwhois_cli.py", line 1055, in lookup_rdap
    ret = self.obj.lookup_rdap(**kwargs)
  File "C:\Program Files\Python_2.7\lib\site-packages\ipwhois\ipwhois.py", line 321, in lookup_rdap
    rate_limit_timeout=rate_limit_timeout
  File "C:\Program Files\Python_2.7\lib\site-packages\ipwhois\rdap.py", line 780 , in lookup
    result_net.parse()
  File "C:\Program Files\Python_2.7\lib\site-packages\ipwhois\rdap.py", line 554, in parse
    self.vars[v] = self.json[v].strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by secynic** [comment]
Duplicate of #254
